logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: info

server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      consul:
        enabled: true
        discovery:
          # get only the services that are passing the health check
          query-passing: true
          # the following defaults to true anyway, added below to facilitate trying false
          register: true
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET, POST
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
      loadbalancer:
        ribbon:
          # even though we excluded the dependency, its nice to be explicit here
          enabled: false
      routes:
        - id: multiplcation
          uri: lb://multiplication
          predicates:
            - Path=/challenges/**,/attempts,/attempts/**,/users/**
        - id: gamification
          uri: lb://gamification
          predicates:
            - Path=/leaders

